version: '3'

services:
  web:
    image: php:7.2-apache
    volumes:
      - ./web:/var/www/html
    ports:
      - 5000:80
  
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
  
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data

volumes:
  redis: {}
